image: java:latest

stages:
    - build
#    - test
    
build:
    stage: build
    script: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac Application.java
    artifacts:
        paths:
            - Application.*
            - jSerialComm-2.5.0.jar
            - json-simple-1.1.jar

#test:
#    stage: test
#    script: /usr/lib/jvm/java-8-openjdk-amd64/bin/java control.Application
